title: The Legolas Code
subtitle: v. 2.0.5 - stable
email: niels.claes@kuleuven.be
baseurl: /
description: The Legolas code
permalink: pretty
minimal_mistakes_skin: air
search: true
footer:
  links:
  - label: The Legolas code on GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/n-claes/legolas
remote_theme: mmistakes/minimal-mistakes
plugins:
- jekyll-feed
- jekyll-include-cache
exclude:
- Gemfile
- Gemfile.lock
include:
- _static
- _modules
- _sources
